spring.application.name=System Payout
spring.jpa.database=POSTGRESQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DB_USER_POSTGRES}:${DB_PASSWORD_POSTGRES}@aws-1-sa-east-1.pooler.supabase.com:5432/postgres